решение для гистограммы
js-tasks-ru/htmlcss-20231027_olesja-a92 pull request #10
Opened 2023-11-11 13:30 UTC by olesjagorning

2023-11-11 13:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 13:30 UTC, GSemikozov requested changes

2023-11-12 13:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-decoration: none;
margin-top: 3px :)

2023-11-12 13:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 39px;
margin-top (отталкивается от соседей, а не используем для внутреннего форматирования)

2023-11-12 13:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__wrapper div{
.histogram__column

2023-11-12 13:51 UTC, olesjagorning commented
добавила исправления

2023-11-12 14:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-13 15:19 UTC, GSemikozov approved these changes

2023-11-13 15:19 UTC, merged