Skeleton
js-tasks-ru/htmlcss-20231027_olesja-a92 pull request #11
Opened 2023-11-11 14:28 UTC by olesjagorning

2023-11-11 14:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 13:34 UTC, GSemikozov requested changes

2023-11-12 13:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_width40{
лучше более семантические классы по типу .skeleton__line_small etc

2023-11-12 13:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__right">
skeleton__column, и если стили не нужны, то можно оставить просто div

2023-11-12 13:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 13:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-12 14:16 UTC, olesjagorning commented
добавила исправления

2023-11-12 14:18 UTC, GSemikozov approved these changes

2023-11-12 14:18 UTC, merged