решение для модального окна
js-tasks-ru/htmlcss-20231027_olesja-a92 pull request #13
Opened 2023-11-17 17:54 UTC by olesjagorning

2023-11-17 17:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-18 20:55 UTC, GSemikozov requested changes

2023-11-18 20:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    height: 100%;
остается еще фон здесь через rgba указать - и будет расота)

2023-11-18 20:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay{
и тогда этот элемент - лишний, можно удалить

2023-11-18 20:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__close:before{
лучше просто как отдельный элемент

2023-11-20 17:10 UTC, olesjagorning commented
добавлены исправления

2023-11-20 20:16 UTC, GSemikozov approved these changes

2023-11-20 20:16 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-11-20 20:17 UTC, GSemikozov approved these changes

2023-11-20 20:18 UTC, merged