решение для чекбоксов
js-tasks-ru/htmlcss-20231027_olesja-a92 pull request #21
Opened 2023-12-04 09:43 UTC by olesjagorning

2023-12-04 09:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-04 09:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-05 20:45 UTC, GSemikozov requested changes

2023-12-05 20:45 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-group{
такие же вспомогательные стили не добавляем в файлы компонентов) если сильно хо - тогда отдельным файлом или инлайном в хтмл странице с задачей)

2023-12-07 07:14 UTC, olesjagorning commented
добавила исправление

2023-12-09 20:59 UTC, GSemikozov approved these changes

2023-12-09 20:59 UTC, merged