решение для toggler
js-tasks-ru/htmlcss-20231027_olesja-a92 pull request #23
Opened 2023-12-04 10:54 UTC by olesjagorning

2023-12-04 10:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-04 10:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-04 10:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-05 20:47 UTC, GSemikozov requested changes

2023-12-05 20:47 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggle-group{
см МР с чекбоксом

2023-12-07 07:36 UTC, olesjagorning commented
добавлено исправление

2023-12-09 21:00 UTC, GSemikozov approved these changes

2023-12-09 21:00 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-12-09 21:01 UTC, GSemikozov approved these changes

2023-12-09 21:02 UTC, merged